import pandas as pd


def read_pyrosci(filename):
    """Import the text files generated by PyroScience Workbench as a
    pandas DataFrame."""
    # Figure out how many rows to skip
    with open(filename, "r", encoding="unicode_escape") as f:
        lines = f.read().splitlines()
    i = 0
    sensor_type = "Unknown"
    while not lines[i].startswith("Date"):
        if lines[i].startswith("#Device"):
            if "Pico" in lines[i]:
                sensor_type = "Pico"
            elif "AquapHOx" in lines[i]:
                sensor_type = "AquapHOx"
            else:
                print("Unknown sensor.")      
        i += 1
    assert sensor_type !=  "Unknown"
    # Import data file
    data = pd.read_table(filename, skiprows=i, encoding="unicode_escape")
    # Rename columns
    rn = {"Pico":
        {
        "Date [A Ch.1 Main]": "date",
        "Time [A Ch.1 Main]": "time",
        " dt (s) [A Ch.1 Main]": "seconds",
        "pH [A Ch.1 Main]": "pH",
        "Sample Temp. (°C) [A Ch.1 CompT]": "temperature",
        "dphi (°) [A Ch.1 Main]": "dphi",
        "Signal Intensity (mV) [A Ch.1 Main]": "signal_intensity",
        "Ambient Light (mV) [A Ch.1 Main]": "ambient_light",
        "ldev (nm) [A Ch.1 Main]": "ldev",
        "Status [A Ch.1 Main]": "status_pH",
        "Status [A Ch.1 CompT]": "status_temperature",
    }
    }
    data = data.rename(columns=rn[sensor_type])
    # Wrangle datetime
    data["datetime"] = data.date + " " + data.time
    data["datetime"] = pd.to_datetime(
        data.datetime, format="%d-%m-%Y %H:%M:%S.%f"
    )
    # Drop NaNs and unnecessary columns
    data.dropna()
    cols = [
        k for k in rn[sensor_type].values()
    ]
    cols = ['datetime', *cols]
    data = data[cols]
    return data
